#!/bin/sh

sxhkd &

wmname LG3D
# Path for panel
export PATH=$PATH:$HOME/.config/bspwm 

export PANEL_HEIGHT=32
export PANEL_FONT=Aller-7
export COLOR_DEFAULT_FG=#fff
export COLOR_DEFAULT_BG=#2c3e50

bspc config border_width		5
bspc config window_gap			20

bspc config split_ratio          	0.52
bspc config borderless_monocle		true
bspc config gapless_monocle		true
bspc config focus_by_distance		true
bspc config history_aware_focus		true

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a Chromium desktop=^2
bspc rule -a Spotify desktop=^5 floating=on

xsetroot -cursor_name left_ptr&
feh --bg-fill $HOME/Pictures/Wallpapers/geneve.png &

panel &
