#!/usr/bin/env bash

batpath="/sys/class/power_supply/BAT"

w=$(awk '{printf "%.1f", $1*10^-6}' "$batpath"?/power_now)
status=$(cat "$batpath"?/status)

class=""
if [ "$status" != "Charging" ]; then
  (( $(echo "${w} >= 7"| bc -l) ))&& class="medium"
  (( $(echo "${w} >= 10"| bc -l) ))&& class="high"
else
  w="-$w"
fi

echo "$w"
echo ""
echo "$class"
