#!/usr/bin/env zsh

mouse="$(upower -e | grep mouse)"
model=""
dot='\xE2\x97\x8F'

updatemodel() {
  model="$(upower -i $mouse | awk '(/model/) {$1=""; print $0}' | sed 's/ //')"
}

updatemodel

printdots() {
  state="ok";
  offdot="<span foreground='grey'>$dot</span>"

  dot1="$dot"
  dot2="$dot"
  dot3="$dot"
  
  if [ "$1" -le "10" ]; then
    state="critical"
  else
    if [ "$1" -lt "33" ]; then
      dot2="$offdot"
    fi
    if [ "$1" -lt "66" ]; then
      dot3="$offdot"
    fi
  fi

  printf "{ \"text\": \"$dot3 $dot2 $dot1\", \"tooltip\": \"$model: $1%%\", \"percentage\": $1, \"class\": \"$state\" }\n"
}

if ! [ -z "$mouse" ]; then
  perc="$(upower -i $mouse | grep percentage | awk '{print $2}')"

  printdots "${perc%?}"
fi

# This is done to kill upower upon exit
upower -m > >(while read line ; do
  case $line in
    *"mouse"* )
      if [ "$(echo $line | awk '{print $3}')" = "removed:" ]; then
	printf "{ \"text\": \"\" }\n"
      else
	mouse="$(echo $line | awk '{print $4}')"
	updatemodel

	perc="$(upower -i $mouse | grep percentage | awk '{print $2}')"

	printdots "${perc%?}"
      fi
      ;;
    * )
      ;;
  esac
done)
wait $!
