#!/usr/bin/sh

state=$("$HOME/.config/waybar/scripts/tlp" | awk 'NR==3 {print $0}')

case "$state" in
  "BAT manual")
    sudo tlp ac
    ;;
  "AC manual")
    sudo tlp start
    ;;
  "BAT auto")
    sudo tlp ac
    ;;
  "AC auto")
    sudo tlp bat
    ;;
  *)
    echo "Unknown state $state"
    ;;
esac

