#!/usr/bin/env bash

rpm="$(grep speed /proc/acpi/ibm/fan | awk '{print $2}')"

class="low"
(( $(echo "${rpm}>3490"|bc -l) )) && class="medium"
(( $(echo "${rpm}>3990"|bc -l) )) && class="high"

if [ "$rpm" -ne 0 ]; then
  echo "&#xf863;"
  echo "$rpm RPM"
  echo "$class"
fi
