#!/usr/bin/env bash

while :
do
  updates=$(checkupdates+aur | wc -l)

  if [ "$updates" -gt "0" ]; then
    echo "$updates/$(pacman -Q | wc -l)"
    #echo "$updates"
    #echo "high"
  fi
  sleep 1800
done
