input type:touchpad {
  tap enabled
  drag_lock enabled
  middle_emulation enabled
  dwt disabled
}

input type:keyboard {
  xkb_numlock enabled
  xkb_layout us,it
  xkb_variant altgr-intl
  #xkb_options ctrl:swapcaps,altwin:swap_alt_win
} 

# Zi slim keyboard in mac mode
input "1452:591:HS6209_USB_Dongle" {
  xkb_options ctrl:swapcaps
}

# Zi keyboard
input "65534:11:www.hfd.cn_AKKO_Keyboard" { 
  xkb_options altwin:swap_alt_win
}

input "1133:50184:Logitech_USB_Trackball" {
  scroll_method on_button_down
  scroll_button button8
  middle_emulation enabled
}

input 1133:45081:MX_Master_2S_Mouse {
  scroll_factor 0.3
}
